name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: panytsch/emate-react/emate-prod
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile-prod
          tags: latest
      - name: Deploy package to digitalocean
          uses: cross-the-world/ssh-pipeline@master
          env:
            GITHUB_USERNAME: ${{ github.actor }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            host: ${{ secrets.DO_HOST }}
            user: ${{ secrets.DO_USERNAME }}
            pass: ${{ secrets.DO_PASSWORD }}
            port: ${{ secrets.DO_SSH_PORT }}
            envs: GITHUB_USERNAME, GITHUB_TOKEN
            script: |
              docker stop $(docker ps -a -q)
              docker login ghcr.io -u $GITHUB_USERNAME -p $GITHUB_TOKEN
              docker pull ghcr.io/panytsch/emate-react/emate-prod:latest
              docker run -dit -p 80:80 ghcr.io/panytsch/emate-react/emate-prod:latest
